spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookshop}
    username: ${SPRING_DATASOURCE_USERNAME:bookshop}
    password: ${SPRING_DATASOURCE_PASSWORD:bookshop}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
server:
  port: 8081
