spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bookshop}
    username: ${DB_USER:bookshop}
    password: ${DB_PASSWORD:bookshop}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
server:
  port: 8080
