version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bookshop
      POSTGRES_USER: bookshop
      POSTGRES_PASSWORD: bookshop
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookshop"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bookshop
      SPRING_DATASOURCE_USERNAME: bookshop
      SPRING_DATASOURCE_PASSWORD: bookshop
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
