version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bookshop
      POSTGRES_USER: bookshop
      POSTGRES_PASSWORD: bookshop
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookshop"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bookshop
      DB_USER: bookshop
      DB_PASSWORD: bookshop
    ports:
      - "8080:8080"
